main: com.moshu.simpleadvertising.Main
name: SimpleAdvertising
version: ${project.version}
author: Moshu
website: http://mc.b-zone.ro
softdepend: [Essentials, Vault, PlaceholderAPI]
#api-version: "1.15"

commands:
  ad:
    description: Display an announcement on the chat
  broadcast:
    description: Broadcast text in chat
  points:
    description: Use points.
permissions:
  simplead.ad:
    default: op
    description: Display an announcement
  simplead.broadcast:
    default: op
    description: Title & chat broadcasting
  simplead.reload:
    default: op
    description: Reload the plugin
  simplead.help:
    default: true
    description: Allow players to see /help page
  simplead.admin:
    default: op
    description: Admin
  simplead.points:
    default: op
    description: Sees his own points
  simplead.debug:
    default: op
    description: Use debug command